[module]
	[[module.imports]]
		path = "github.com/adityatelange/hugo-PaperMod"
		disable = false

    [[module.imports]]
        path = "github.com/tnarik/hugo-homebrewery-theme_props"
        disable = false
